### ISSUE TITLE
1.0.0 doesn't have the alpha fix

### ISSUE THREAD

**Issue by ElvenSpellmaker** [whoops-php/phalcon#3]
Which means we have to tie our branch to `dev-master#dc63778f9a8d0e8bd7d2eb2c23ba3f3b28060af2` instead of a version. =)

**Comment by denis-sokolov** [comment]
Hi, @ElvenSpellmaker, thanks for speaking up! Could you clarify this in a little bit more detail, please?

**Comment by ElvenSpellmaker** [comment]
Hey @denis-sokolov, you've made a fix for the changes to Whoops https://github.com/whoops-php/phalcon/commit/dc63778f9a8d0e8bd7d2eb2c23ba3f3b28060af2 and it's not tagged as a release on github/packagist.

It'd be nice to bump the version number by tagging a new release so that we can use the new version in our composer files.

**Comment by sergeyklay** [comment]
+1

**Comment by denis-sokolov** [comment]
Ah, this makes sense. thank you. [Marked 2.0.0](https://packagist.org/packages/whoops/phalcon).
